import { useState } from "react";
import { LoaderCircle } from "lucide-react";
import Badge from "../components/Badge";
import Notice from "../components/Notice";
import { api } from "../lib/api";
const sample = JSON.stringify([{ title: "Portable desk lamp", description: "USB rechargeable LED desk lamp with three brightness settings and a flexible neck. Includes charging cable.", category: "Home & Office", price: 24.99, attributes: { color: "White" }, seller: "Example Seller", tags: ["lighting"] }], null, 2);
export default function BatchImport({ refresh, setPage, openReview }) {
  const [text, setText] = useState(sample), [result, setResult] = useState(null), [error, setError] = useState(""), [saving, setSaving] = useState(false), [reviewing, setReviewing] = useState(false);
  async function submit(event) { event.preventDefault(); setSaving(true); setError(""); try { const listings = JSON.parse(text); const data = await api("/listings/batch", { method: "POST", body: JSON.stringify({ listings }) }); setResult(data.results); refresh(); } catch (err) { setError(err instanceof SyntaxError ? "Enter a valid JSON array." : err.message); } finally { setSaving(false); } }
  async function runReviews() { const listingIds = result.filter((row) => row.status === "ready" && row.listing?._id).map((row) => row.listing._id); if (!listingIds.length) return; setReviewing(true); setError(""); try { const data = await api("/reviews/batch", { method: "POST", body: JSON.stringify({ listingIds }) }); setResult(result.map((row) => { const outcome = data.results.find((item) => item.listingId === row.listing?._id); return outcome ? { ...row, reviewStatus: outcome.status, review: outcome.review, reviewError: outcome.error } : row; })); refresh(); } catch (err) { setError(err.message); } finally { setReviewing(false); } }
  function loadFile(event) { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => setText(String(reader.result)); reader.onerror = () => setError("Could not read that file."); reader.readAsText(file); }
  return <><div className="page-heading"><div><p className="eyebrow">Bulk intake</p><h1>Batch import</h1><p>Add or upload up to 20 listings as a JSON array. Each is validated separately.</p></div></div><Notice error={error} /><form className="section" onSubmit={submit}><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-600">Upload a JSON file, or paste its contents below.</p><label className="button secondary small cursor-pointer">Choose JSON file<input className="hidden" type="file" accept="application/json,.json" onChange={loadFile} /></label></div><label><span>Listings JSON</span><textarea className="font-mono text-xs" rows="17" value={text} onChange={(e) => setText(e.target.value)} /></label><div className="mt-4 flex justify-end"><button className="button primary" disabled={saving}>{saving && <LoaderCircle className="animate-spin" size={16} />} Import listings</button></div></form>{result && <section className="section mt-6"><div className="section-title"><div><h2>Import results</h2><p>Run policy reviews for ready listings, then open individual results.</p></div><div className="flex gap-3"><button className="text-button" onClick={() => setPage("Review queue")}>Open queue</button><button className="button primary small" disabled={reviewing || !result.some((row) => row.status === "ready" && !row.reviewStatus)} onClick={runReviews}>{reviewing && <LoaderCircle className="animate-spin" size={15} />} Run reviews</button></div></div>{result.map((row, i) => <div key={i} className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 py-3 text-sm"><span>{row.title}{row.reviewError && <small className="ml-2 text-red-700">{row.reviewError}</small>}</span><div className="flex items-center gap-2"><Badge tone={row.reviewStatus === "complete" ? "bg-emerald-50 text-emerald-700" : row.status === "ready" ? "bg-blue-50 text-blue-700" : "bg-red-50 text-red-700"}>{row.reviewStatus || row.status}</Badge>{row.review && <button type="button" className="text-button" onClick={() => openReview(row.review)}>Open result</button>}</div></div>)}</section>}</>;
}
