import { useState } from "react";
import { CheckCircle2, LoaderCircle } from "lucide-react";
import Notice from "../components/Notice";
import { api } from "../lib/api";
import { CATEGORIES, emptyListing } from "../lib/constants";
export default function ListingForm({ refresh, onCreated }) {
  const [form, setForm] = useState(emptyListing), [errors, setErrors] = useState({}), [saving, setSaving] = useState(false), [message, setMessage] = useState("");
  const set = (field, value) => setForm({ ...form, [field]: value });
  async function submit(event) { event.preventDefault(); setSaving(true); setErrors({}); setMessage(""); try { const listing = await api("/listings", { method: "POST", body: JSON.stringify(form) }); setMessage("Listing created and ready for review."); setForm(emptyListing); refresh(); onCreated(listing); } catch (error) { setErrors(error.errors || {}); setMessage(error.message); } finally { setSaving(false); } }
  const input = (label, key, props = {}) => <label><span>{label}</span><input value={form[key]} onChange={(e) => set(key, e.target.value)} {...props} />{errors[key] && <small className="field-error">{errors[key]}</small>}</label>;
  return <><div className="page-heading"><div><p className="eyebrow">Intake</p><h1>Create listing</h1><p>Required checks are applied before an AI review can begin.</p></div></div><Notice error={message && !message.includes("ready") ? message : ""} />{message.includes("ready") && <div className="mb-5 flex gap-2 border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800"><CheckCircle2 size={17} />{message}</div>}<form className="section form-grid" onSubmit={submit}><div className="col-span-full section-title"><div><h2>Listing details</h2><p>Fields marked here are used in policy review.</p></div></div>{input("Title", "title", { placeholder: "e.g. Adjustable aluminum laptop stand" })}<label><span>Category</span><select value={form.category} onChange={(e) => set("category", e.target.value)}>{CATEGORIES.map((category) => <option key={category}>{category}</option>)}</select>{errors.category && <small className="field-error">{errors.category}</small>}</label>{input("Price", "price", { type: "text", inputMode: "decimal", placeholder: "0.00" })}{input("Seller", "seller", { placeholder: "Seller or business name" })}<label className="col-span-full"><span>Description</span><textarea rows="6" value={form.description} onChange={(e) => set("description", e.target.value)} placeholder="Describe the item or service, condition, delivery, and material limitations." />{errors.description && <small className="field-error">{errors.description}</small>}</label><label><span>Attributes</span><textarea rows="4" value={form.attributes} onChange={(e) => set("attributes", e.target.value)} placeholder={"color: Black\nmaterial: Aluminum"} /><small>One “name: value” pair per line.</small></label>{input("Optional tags", "tags", { placeholder: "office, ergonomic, stand" })}<div className="col-span-full flex justify-end border-t border-slate-200 pt-5"><button className="button primary" disabled={saving}>{saving && <LoaderCircle className="animate-spin" size={16} />} Submit for review</button></div></form></>;
}
