import Badge from "../components/Badge";
import Finding from "../components/Finding";
import { statusClass } from "../lib/constants";
export default function ReviewDetails({ review, onAction, back }) {
  if (!review) return null;
  const listing = review.listing;
  const policyMap = Object.fromEntries((review.policySections || []).map((section) => [section.code, section]));
  return <><div className="page-heading"><div><button className="back" onClick={back}>← Back to history</button><p className="eyebrow">Review result</p><h1>{listing?.title}</h1><p>Reviewed {new Date(review.createdAt).toLocaleString()} with {review.model}.</p></div></div><section className="section"><div className="section-title"><div><h2>Listing information</h2><p>{listing?.category} · {listing?.seller} · ${listing?.price?.toFixed(2)}</p></div><Badge tone={statusClass[listing?.status] || "bg-slate-100"}>{listing?.status?.replace("_", " ")}</Badge></div><div className="listing-copy"><div><p className="label">Description</p><p>{listing?.description}</p></div><div><p className="label">Attributes</p><p>{Object.entries(listing?.attributes || {}).map(([key, value]) => `${key}: ${value}`).join(" · ") || "None supplied"}</p></div><div><p className="label">Tags</p><p>{listing?.tags?.join(", ") || "None supplied"}</p></div></div></section><section className="mt-7"><div className="mb-4"><p className="eyebrow">AI findings</p><h2 className="text-xl font-semibold">{review.findings.length ? `${review.findings.length} policy-grounded issue${review.findings.length === 1 ? "" : "s"}` : "No policy-grounded issues found"}</h2><p className="mt-1 text-sm text-slate-600">{review.summary}</p></div>{review.findings.map((finding, index) => <Finding key={index} finding={finding} index={index} policyMap={policyMap} onAction={onAction} />)}{!review.findings.length && <div className="section text-sm text-slate-600">The AI found no policy-grounded issues in the retrieved policy context. Human review remains responsible for the final decision.</div>}</section><section className="section mt-7"><div className="section-title"><div><h2>Policy context used</h2><p>Only these retrieved sections were supplied to the AI reviewer.</p></div></div><div className="grid gap-3 md:grid-cols-2">{review.policySections.map((policy) => <div key={policy._id} className="border border-slate-200 p-4"><p className="font-semibold">{policy.code} — {policy.title}</p><p className="mt-1 text-sm text-slate-600">{policy.content}</p></div>)}</div></section></>;
}
