import { useState } from "react";
import Badge from "./Badge";
import { severityClass } from "../lib/constants";
export default function Finding({ finding, index, policyMap, onAction }) {
  const [editing, setEditing] = useState(false), [revision, setRevision] = useState(finding.editedRevision || finding.suggestedRevision), [saving, setSaving] = useState(false);
  const policy = policyMap[finding.policyCode];
  async function act(action) { setSaving(true); try { await onAction(index, action, action === "edited" ? revision : ""); setEditing(false); } finally { setSaving(false); } }
  const revised = finding.action === "edited" ? finding.editedRevision : finding.suggestedRevision;
  return <article className="finding"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h3>{finding.issue}</h3><Badge tone={severityClass[finding.severity]}>{finding.severity}</Badge><Badge tone="bg-slate-100 text-slate-600">{finding.confidence}% confidence</Badge>{finding.action !== "pending" && <Badge tone="bg-indigo-50 text-indigo-700">{finding.action}</Badge>}</div><p className="source-quote">“{finding.sourceText}”</p></div></div><div className="finding-grid"><div><p className="label">Explanation</p><p>{finding.explanation}</p></div><div><p className="label">Evidence classification</p><p>{finding.evidenceType === "confirmed" ? "Confirmed in listing text" : "Unverifiable claim — not asserted as false"}</p></div><div><p className="label">Policy reference</p><p><strong>{finding.policyCode}</strong>{policy ? ` — ${policy.title}` : ""}</p></div></div><div className="comparison"><div><p className="label">Original</p><p>{finding.sourceText}</p></div><div><p className="label">Suggested revision</p>{editing ? <textarea value={revision} onChange={(e) => setRevision(e.target.value)} rows="3" /> : <p>{revised || "No wording change proposed."}</p>}</div></div>{finding.action === "pending" || editing ? <div className="mt-4 flex flex-wrap gap-2">{editing ? <><button className="button primary small" disabled={saving} onClick={() => act("edited")}>{saving ? "Saving…" : "Save edited revision"}</button><button className="button secondary small" onClick={() => { setEditing(false); setRevision(finding.suggestedRevision); }}>Cancel</button></> : <><button className="button success small" disabled={saving} onClick={() => act("approved")}>Approve</button><button className="button secondary small" disabled={saving} onClick={() => setEditing(true)}>Edit</button><button className="button danger small" disabled={saving} onClick={() => act("rejected")}>Reject</button></>}</div> : null}</article>;
}
